define({
  root: {
    _widgetLabel: "Attribute Table",
    ok: "OK",
    cancel: "Cancel",
    exportMessage: "Export data to CSV file?",
    exportFiles: "Export to CSV",
    options: "Options",
    zoomto: "Zoom to",
    highlight: "Highlight Graphics",
    selectAll: "Select Records in All Pages",
    selectPage: "Select Records in Current Page",
    clearSelection: "Clear Selection",
    filterByExtent: "Filter by Map Extent",
    refresh: "Refresh",
    selected: "selected",
    transparent: "Transparent Mode",
    indicate: "Locate Selection",
    columns: "Show/Hide Columns",
    selectionSymbol: "Selection Symbol",
    closeMessage: "Hide Table (expand it again from the bottom)",
    dataNotAvailable: "Data not available!<br>Click [Refresh] button to try again.",
    openTableTip: "Open Attribute Table",
    closeTableTip: "Hide Attribute Table"
  },
  "ar": false,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": false,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-br": true,
  "pt-pt": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  "zh-cn": true
});