define({

    _widgetLabel: "Atribuuditabel",
    ok: "OK",
    cancel: "Tühista",
    exportMessage: "Kas soovite eksportida andmed CSV faili?",
    exportFiles: "Ekspordi CSV faili",
    options: "Valikud",
    zoomto: "Suumi",
    highlight: "Tõsta graafika esile",
    selectAll: "Vali kõigi lehtede kirjed",
    selectPage: "Vali praeguse lehe kirjed",
    clearSelection: "Tühista valik",
    filterByExtent: "Filtreeri kaardi ulatuse järgi",
    refresh: "Värskenda",
    selected: "valitud",
    transparent: "Läbipaistvuse režiim",
    indicate: "Paiguta valik",
    columns: "Näita/Peida veerud",
    selectionSymbol: "Valiku sümbol",
    closeMessage: "Peida tabel (laienda seda uuesti altpoolt)",
    dataNotAvailable: "Andmed ei ole saadaval!<br>Uuesti proovimiseks klikkige nuppu [Värskenda]",
    openTableTip: "Ava atribuutide tabel",
    closeTableTip: "Peida atribuutide tabel"
});