define({

    _widgetLabel: "Tabel de atribute",
    ok: "OK",
    cancel: "Anulare",
    exportMessage: "Exportaţi datele în fişier CSV?",
    exportFiles: "Export în CSV",
    options: "Opţiuni",
    zoomto: "Transfocare la",
    highlight: "Evidenţiere elemente grafice",
    selectAll: "Selectare înregistrări din toate paginile",
    selectPage: "Selectare înregistrări din pagina curentă",
    clearSelection: "Golire selecţie",
    filterByExtent: "Filtrare după extinderea hărţii",
    refresh: "Reîmprospătare",
    selected: "selectat",
    transparent: "Mod Transparent",
    indicate: "Selectare locaţie",
    columns: "Afişare/Ascundere coloane",
    selectionSymbol: "Simbol pentru selectare",
    closeMessage: "Ascundere tabel (se extinde din nou de jos)",
    dataNotAvailable: "Nu există date disponibile!<br>Faceţi clic pe butonul [Reîmprospătare] pentru a încerca din nou.",
    openTableTip: "Deschidere tabel de atribute",
    closeTableTip: "Ascundere tabel de atribute"
});