define({

    _widgetLabel: "Tabela de Atributos",
    ok: "OK",
    cancel: "Cancelar",
    exportMessage: "Exportar dados para arquivo CSV?",
    exportFiles: "Exportar para CSV",
    options: "Opções",
    zoomto: "Zoom para",
    highlight: "Destacar Gráficos",
    selectAll: "Selecionar Registros em Todas as Páginas",
    selectPage: "Selecionar Registros na Página Atual",
    clearSelection: "Limpar Seleção",
    filterByExtent: "Fltrar por Extensão do Mapa",
    refresh: "Atualizar",
    selected: "selecionado",
    transparent: "Modo Transparente",
    indicate: "Localizar Seleção",
    columns: "Mostrar/Ocultar Colunas",
    selectionSymbol: "Seleção de Símbolo",
    closeMessage: "Ocultar Tabela (expada novamente na parte inferior)",
    dataNotAvailable: "Dados não disponíveis!<br>Clique no botão [Atualizar] para tentar noamente.",
    openTableTip: "Abrir Tabela de Atributo",
    closeTableTip: "Ocultar Tabela de Atributos"
});