define({
  root: {
    instruction: "Define the content that will display on the splash screen of your application. The splash screen appears before the application loads. ",
    defaultContent: "Add text, links, and small graphics here.",
    requireConfirm: "Require confirmation to continue",
    confirmLabel: "Confirmation Texts: ",
    defaultConfirmText: "I agree to the above terms and conditions"
  },
  "ar": false,
  "cs": false,
  "da": false,
  "de": false,
  "es": false,
  "et": false,
  "fi": false,
  "fr": false,
  "he": false,
  "it": false,
  "ja": false,
  "ko": false,
  "lt": false,
  "lv": false,
  "nb": false,
  "nl": false,
  "pl": false,
  "pt-br": false,
  "pt-pt": false,
  "ro": false,
  "ru": false,
  "sv": false,
  "th": false,
  "tr": false,
  "zh-cn": false
});