define({

    state: "افتراضيًا، سيتم عرض الإحداثيات في النظام الإحداثي للخريطة الحالية. للحصول على الإحداثيات في أنظمة إحداثية أخرى، سيتعين إضافتها وتحديد التحويلات المناسبة.",
    outputUnit: "الوحدة الناتجة",
    wkid: "WKID الناتجة",
    label: "اسم النظام الإحداثي الناتج",
    transformationWkid: 'تحويل WKID',
    transformationLabel: 'تسمية التحويل',
    transformForward: 'تحويل للأمام',
    actions: "الأفعال",
    warning: "الرجاء إدخال الإسناد المكاني الصحيح WKID!",
    tfWarning: "الرجاء إدخال تحويل سطح الأنساب الصحيح WKID!",
    spinnerLabel: "تحويل لإحداثيات إلى: ",
    decimalPlace: "الأماكن العشرية",
    separator: "إظهار ألف فاصل",
    getVersionError: "يتعذر الحصول على إصدار خدمة هندسة الشكل",

    add: "إضافة النظام الإحداثي الناتج",
    edit: "تحرير النظام الإحداثي",
    output: "النظام الإحداثي الناتج",
    cName: "اسم النظام الإحداثي",
    units: "وحدات العرض: ",
    datum: "تحويل مرجع إسناد",
    tName: "اسم التحويل",
    forward: "استخدام التحويل الأمامي",
    ok: "موافق",
    cancel: 'إلغاء الأمر',
    olderVersion: "لا تدعم خدمة هندسة الشكل عملية التحويل",
    REPEATING_ERROR: " يوجد النظام الإحداثي في القائمة الناتجة.",

    Default: "الوضع الافتراضي",
    Inches: "بوصة",
    Foot: "قدم",
    Yards: "ياردات",
    Miles: "أميال",
    Nautical_Miles: "ميل بحري",
    Millimeters: "ميليمتر",
    Centimeters: "سنتيمتر",
    Meter: "متر",
    Kilometers: "كيلومترات",
    Decimeters: "ديسيميتر",
    Decimal_Degrees: "درجات عشرية",
    Degree_Minutes_Seconds: "درجات دقائق ثواني",
    MGRS: "MGRS",
    USNG: "USNG"
});