define({
  root: {
    placeholder: "Placeholder Text",
    url: "Geocoder URL",
    name: "Geocoder Name",
    example: "Example",
    singleLineFieldName: "SingleLineFieldName",
    portalConnectionError: 'Can not get the configurations of geocoder from portal',
    actions: "Actions",
    warning: "Incorrect Service",
    instruction: "Establish the geocoders that will be used in this widget. Click Add Geocoder to reference a URL, specify a user friendly name, and set other properties. You can also reorder, configure, or delete your geocoders below.",
    add: "Add Geocoder",
    edit: "Edit Geocoder",
    ok: "OK",
    cancel: "Cancel",
    geocoderNamePlaceHolder: "My Geocoder",
    geocodePlaceHolder: "Find address or place",
    REPEATING_ERROR: "The following fields are repeated: "
  },
  "ar": false,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": false,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-br": true,
  "pt-pt": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  "zh-cn": true
});