define({
  root: {
    label: "Layer",
    show: "Show",
    actions: "Configure Layer Fields",
    field: "Field",
    alias: "Alias",
    visible: "Visible",
    linkField: "Link Field",
    noLayers: "No feature layers available",
    back: "Back",
    exportCSV: "Allow exporting to CSV",
    restore: "Restore to default value",
    ok: "OK",
    result: "Saved successfully",
    warning: "Check to show this layer in table first most.",

    fieldName: "Name",
    fieldAlias: "Alias",
    fieldVisibility: "Visibility",
    fieldActions: "Actions"
  },
  "ar": false,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": false,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-br": true,
  "pt-pt": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  "zh-cn": true
});