define({
  root: {
    _widgetLabel: "Splash",
    welcomeMessage: "Welcome to ArcGIS Web Application!",
    licenceAgree: "I agree to",
    licenceTerm: "ArcGIS Web Application Terms",
    labelContinue: "Continue",
    errorString: "* You need to agree to the licence to continue.",
    notShowAgain: "Do not show this splash screen again.",
    ok: "OK",
    cancel: "Cancel"
  },
  "ar": false,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": false,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-br": true,
  "pt-pt": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  "zh-cn": true
});