define({
  root: {
    _widgetLabel: "Layer List",
    titleBasemap: 'Basemaps',
    titleLayers: 'Operational Layers',
    labelLayer: 'Layer Name',
    itemZoomTo: 'Zoom to',
    itemTransparency: 'Transparency',
    itemTransparent: 'Transparent',
    itemOpaque: 'Opaque',
    itemMoveUp: 'Move up',
    itemMoveDown: 'Move down',
    itemDesc: 'Description',
    itemDownload: 'Download',
    itemToAttributeTable: 'Open Attribute Table'
  },
  "ar": false,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": false,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-br": true,
  "pt-pt": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  'zh-cn': true
});
